#define RGX_FW_FILENAME "rgx.fw.signed"
#define LINUX 
#define PVR_BUILD_DIR "mt8173_android"
#define PVR_BUILD_TYPE "release"
#define PVRSRV_MODNAME "pvrsrvkm"
#define SUPPORT_RGX 1
#define RELEASE 
#define RGX_BVNC_CORE_KM_HEADER "cores/rgxcore_km_4.40.2.51.h"
#define RGX_BNC_CONFIG_KM_HEADER "configs/rgxconfig_km_4.V.2.51.h"
#define SUPPORT_DBGDRV_EVENT_OBJECTS 
#define PDUMP_STREAMBUF_MAX_SIZE_MB 16
#define SYS_USING_INTERRUPTS 
#define SUPPORT_RANGEBASED_CACHEFLUSH 
#define SUPPORT_GPUTRACE_EVENTS 
#define GPUVIRT_VALIDATION_NUM_OS 8
#define PVRSRV_GPUVIRT_NUM_OSID  2
#define PVRSRV_GPUVIRT_OSID 0
#define PVRSRV_GPUVIRT_OSID_STR ""
#define PVRSRV_GPUVIRT_FWHEAP_SIZE  4194304
#define PVRSRV_GPUVIRT_FWHEAP_BASE  0
#define FIX_DUSTS_POW_ON_INIT 
#define SUPPORT_LINUX_X86_WRITECOMBINE 
#define SUPPORT_LINUX_X86_PAT 
#define PVR_LINUX_USING_WORKQUEUES 
#define PVR_LINUX_MISR_USING_PRIVATE_WORKQUEUE 
#define PVR_LINUX_TIMERS_USING_WORKQUEUES 
#define PVR_LDM_DRIVER_REGISTRATION_NAME "pvrsrvkm"
#define LDM_PLATFORM 
#define PVRSRV_FULL_SYNC_TRACKING_HISTORY_LEN 256
#define PVR_DUMMY_PAGE_INIT_VALUE 0x00
#define PVRSRV_UNMAP_ON_SPARSE_CHANGE 
#define SUPPORT_PERCONTEXT_FREELIST 
#define HWR_DEFAULT_ENABLED 
#define PVRSRV_ENABLE_PROCESS_STATS 
#define PVR_LINUX_PHYSMEM_MAX_POOL_PAGES 10240
#define PVR_LINUX_PHYSMEM_MAX_EXCESS_POOL_PAGES 32768
#define PVR_DIRTY_PAGECOUNT_FLUSH_THRESHOLD  256
#define PVR_LINUX_HIGHORDER_ALLOCATION_THRESHOLD  256 
#define PVR_LINUX_PHYSMEM_MAX_ALLOC_ORDER_NUM  2 
#define PVR_LINUX_KMALLOC_ALLOCATION_THRESHOLD  16384 
#define SUPPORT_KERNEL_SRVINIT 
#define SUPPORT_DRM 
#define ANDROID 
#define SUPPORT_ION 
#define SUPPORT_DMABUF 
#define DMABUF_IMPORT_PHYSHEAP_ID 0
#define SUPPORT_NATIVE_FENCE_SYNC 
#define SUPPORT_ION 
#define PVR_ANDROID_ION_HEADER "../drivers/staging/android/ion/ion.h"
#define PVR_ANDROID_ION_PRIV_HEADER "../drivers/staging/android/ion/ion_priv.h"
#define PVR_ANDROID_ION_USE_SG_LENGTH 
#define PVR_ANDROID_SYNC_HEADER "../drivers/staging/android/sync.h"
#define MTK_MFG_DVFS 
