/*
 * Copyright (c) 2014 MediaTek Inc.
 * Author: YongWu <yong.wu@mediatek.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */
#ifndef __DTS_IOMMU_PORT_MT2701_H
#define __DTS_IOMMU_PORT_MT2701_H

#define M4U_LARB0_PORTn(n)		(n+0)
#define M4U_LARB1_PORTn(n)		(n+11)
#define M4U_LARB2_PORTn(n)		(n+21)
#define M4U_LARB3_PORTn(n)		(n+44)

#define M4U_PORT_DISP_OVL_0		M4U_LARB0_PORTn(0)
#define M4U_PORT_DISP_RDMA1		M4U_LARB0_PORTn(1)
#define M4U_PORT_DISP_RDMA		M4U_LARB0_PORTn(2)
#define M4U_PORT_DISP_WDMA		M4U_LARB0_PORTn(3)
#define M4U_PORT_MM_CMDQ		M4U_LARB0_PORTn(4)
#define M4U_PORT_MDP_RDMA		M4U_LARB0_PORTn(5)
#define M4U_PORT_MDP_WDMA		M4U_LARB0_PORTn(6)
#define M4U_PORT_MDP_ROTO		M4U_LARB0_PORTn(7)
#define M4U_PORT_MDP_ROTCO		M4U_LARB0_PORTn(8)
#define M4U_PORT_MDP_ROTVO		M4U_LARB0_PORTn(9)
#define M4U_PORT_MDP_RDMA1		M4U_LARB0_PORTn(10)

#define M4U_PORT_VDEC_MC_EXT		M4U_LARB1_PORTn(0)
#define M4U_PORT_VDEC_PP_EXT		M4U_LARB1_PORTn(1)
#define M4U_PORT_VDEC_PPWRAP_EXT	M4U_LARB1_PORTn(2)
#define M4U_PORT_VDEC_AVC_MV_EXT	M4U_LARB1_PORTn(3)
#define M4U_PORT_VDEC_PRED_RD_EXT	M4U_LARB1_PORTn(4)
#define M4U_PORT_VDEC_PRED_WR_EXT	M4U_LARB1_PORTn(5)
#define M4U_PORT_VDEC_VLD_EXT		M4U_LARB1_PORTn(6)
#define M4U_PORT_VDEC_VLD2_EXT		M4U_LARB1_PORTn(7)
#define M4U_PORT_VDEC_TILE_EXT		M4U_LARB1_PORTn(8)
#define M4U_PORT_VDEC_IMG_RESZ_EXT	M4U_LARB1_PORTn(9)

#define M4U_PORT_VENC_RCPU		M4U_LARB2_PORTn(0)
#define M4U_PORT_VENC_REC_FRM		M4U_LARB2_PORTn(1)
#define M4U_PORT_VENC_BSDMA		M4U_LARB2_PORTn(2)
#define M4U_PORT_JPGENC_RDMA		M4U_LARB2_PORTn(3)
#define M4U_PORT_VENC_LT_RCPU		M4U_LARB2_PORTn(4)
#define M4U_PORT_VENC_LT_REC_FRM	M4U_LARB2_PORTn(5)
#define M4U_PORT_VENC_LT_BSDMA		M4U_LARB2_PORTn(6)
#define M4U_PORT_JPGDEC_BSDMA		M4U_LARB2_PORTn(7)
#define M4U_PORT_VENC_SV_COMV		M4U_LARB2_PORTn(8)
#define M4U_PORT_VENC_RD_COMV		M4U_LARB2_PORTn(9)
#define M4U_PORT_JPGENC_BSDMA		M4U_LARB2_PORTn(10)
#define M4U_PORT_VENC_CUR_LUMA		M4U_LARB2_PORTn(11)
#define M4U_PORT_VENC_CUR_CHROMA	M4U_LARB2_PORTn(12)
#define M4U_PORT_VENC_REF_LUMA		M4U_LARB2_PORTn(13)
#define M4U_PORT_VENC_REF_CHROMA	M4U_LARB2_PORTn(14)
#define M4U_PORT_IMG_RESZ		M4U_LARB2_PORTn(15)
#define M4U_PORT_VENC_LT_SV_COMV	M4U_LARB2_PORTn(16)
#define M4U_PORT_VENC_LT_RD_COMV	M4U_LARB2_PORTn(17)
#define M4U_PORT_VENC_LT_CUR_LUMA	M4U_LARB2_PORTn(18)
#define M4U_PORT_VENC_LT_CUR_CHROMA	M4U_LARB2_PORTn(19)
#define M4U_PORT_VENC_LT_REF_LUMA	M4U_LARB2_PORTn(20)
#define M4U_PORT_VENC_LT_REF_CHROMA	M4U_LARB2_PORTn(21)
#define M4U_PORT_JPGDEC_WDMA		M4U_LARB2_PORTn(22)

#endif
