#modify@zte.com.cn 20160408 begin
#
# Makefile for misc devices that really don't fit anywhere else.
#
ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc

obj-y += ili9881_hd720_dsi_vdo_yassycmi.o

#modify@zte.com.cn 20160408 end



